### ISSUE TITLE
I mus do something wrong

### ISSUE THREAD

**Issue by Antheor** [TobiahZ/corona-tools#1]
First for letting us try corona on visual studio code.

No shortcuts seem to work on my windows 7 pc ;((

**Comment by TobiahZ** [comment]
Interesting. It might be a bug (I think there is a problem with the keyboard shortcuts for Mac right now, but that shouldn't effect Windows 7)

Have you tried running the pallet command? Does that work where keyboard shortcuts do not?

**Comment by Antheor** [comment]
The pallet command seems to work indeed. Thx for your answer.

2016-04-26 22:24 GMT+02:00 Tobiah Zarlez <notifications@github.com>:

**Comment by TobiahZ** [comment]
But keyboard shortcut doesn't work on Windows 7? That is a weird bug, not sure the cause. Need to find another windows 7 machine to test. Are any other keyboard shortcuts in vscode not working for you?

Sent from Nine<http://www.9folders.com/>
